spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:~/demo050
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    #url: jdbc:postgresql://localhost:5432/demo
    #username: postgres
    #password: passw0rd
    #driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      poll-interval: 2
      quiet-period: 1

logging:
#  file: logs/demo.log
#    max-size: 10M
  level:
    root: WARN
    org:
      springframework:
        jdbc:
          core: WARN
        web: INFO
        batch: WARN
    com:
      example:
        demo: INFO
  pattern:    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss z}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-20.20logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

application:
  default:
    language: en
  client: # second
    refresh: 180
    languages: ja,en,zh

