spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
      encoding: utf-8
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:~/demo050
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    #url: jdbc:postgresql://localhost:5432/demo
    #username: postgres
    #password: passw0rd
    #driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      poll-interval: 2
      quiet-period: 1

logging:
#  file: logs/demo.log
#    max-size: 10M
  level:
    root: WARN
    org:
      springframework:
        jdbc:
          core: WARN
        web: INFO
        batch: WARN
    com:
      example:
        demo: INFO

application:
  default:
    language: en

