DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;

DROP TABLE IF EXISTS TODOS;
DROP TABLE IF EXISTS TIMES;
DROP TABLE IF EXISTS PLAN_DETAILS;
DROP TABLE IF EXISTS PLANS;
DROP TABLE IF EXISTS PLACES;

CREATE TABLE ROLE(
    ID VARCHAR(16) PRIMARY KEY,
    NAME VARCHAR(128)
);

CREATE TABLE USERS (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(16),
    EXPIRY TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY(ROLE) REFERENCES ROLE(ID)
);

CREATE TABLE TODOS (
    ID SERIAL PRIMARY KEY,
    "VALUE" VARCHAR(32)
);

CREATE TABLE TIMES (
    ID SERIAL PRIMARY KEY,
    "VALUE" VARCHAR(32),
    "DATE" date,
    "TIME" time,
    DATE_WITHOUT TIMESTAMP WITHOUT TIME ZONE,
    OFFSET_WITH TIMESTAMP WITH TIME ZONE
);

CREATE TABLE PLACES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(128),
    TIMEZONE VARCHAR(32)
);

CREATE TABLE PLANS (
  ID SERIAL PRIMARY KEY,
  PLACES_ID INTEGER,
  DATE TIMESTAMP WITHOUT TIME ZONE,
  FOREIGN KEY(PLACES_ID) REFERENCES PLACES(ID)
);

CREATE TABLE PLAN_DETAILS (
  ID SERIAL PRIMARY KEY,
  PLANS_ID INTEGER,
  NAME VARCHAR(128),
  START TIMESTAMP WITHOUT TIME ZONE,
  "END" TIMESTAMP WITHOUT TIME ZONE,
  FOREIGN KEY(PLANS_ID) REFERENCES PLANS(ID)
);


